#!/bin/bash

N=$1
MUESTRA=../muestras/$2
echo borro ${MUESTRA}
rm ${MUESTRA}

for ((i=0; i < $N; i++)) {
        cat ../py/ejs/ej$i  | ../build/tbt >> ${MUESTRA}
}

awk -f ../awk/mean3.awk ../muestras/${MUESTRA}

